aws fix

diff --git a/templates/k8s-validation.yml b/templates/k8s-validation.yml
--- a/templates/k8s-validation.yml
+++ b/templates/k8s-validation.yml
@@ -21,31 +21,42 @@ stages:
 
 # CONFIGURE AWS + KUBECONFIG
 
-    - script: |
+- script: |
 
-        mkdir -p ~/.aws
+    echo "AWS KEY EXISTS"
 
-        cat > ~/.aws/credentials <<EOF
-        [default]
-        aws_access_key_id=$(AWS_ACCESS_KEY_ID)
-        aws_secret_access_key=$(AWS_SECRET_ACCESS_KEY)
-        EOF
+    if [ -z "$(AWS_ACCESS_KEY_ID)" ]
+    then
+      echo "ACCESS KEY missing"
+      exit 1
+    fi
 
-        cat > ~/.aws/config <<EOF
-        [default]
-        region=$(AWS_REGION)
-        output=json
-        EOF
+    if [ -z "$(AWS_SECRET_ACCESS_KEY)" ]
+    then
+      echo "SECRET KEY missing"
+      exit 1
+    fi
 
-        export AWS_PROFILE=default
 
-        aws sts get-caller-identity
+    export AWS_ACCESS_KEY_ID="$(AWS_ACCESS_KEY_ID)"
 
-        aws eks update-kubeconfig \
-        --region $(AWS_REGION) \
-        --name $(EKS_CLUSTER)
+    export AWS_SECRET_ACCESS_KEY="$(AWS_SECRET_ACCESS_KEY)"
 
-      displayName: "Configure Cluster"
+    export AWS_DEFAULT_REGION="$(AWS_REGION)"
+
+
+    aws sts get-caller-identity
+
+
+    aws eks update-kubeconfig \
+      --region $(AWS_REGION) \
+      --name $(EKS_CLUSTER)
+
+  displayName: "Configure Cluster"
+
+    env:
+    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
+    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
 
 # VERIFY
 
